### ISSUE TITLE
Preferences: h2 title looks like foldable/clickable 

### ISSUE THREAD

**Issue by vitaly-zdanevich** [kuanyui/EngineSwitcher#11]
![image](https://github.com/kuanyui/EngineSwitcher/assets/3514015/1463dd99-b91f-4eba-b13e-5bf8d0f1df33)

These triangles looks like I can click and expand something.

**Comment by kuanyui** [comment]
Actually I don't think this is an issue. I just select this as a bullet-liked icon. Also had tried other characters when implementing options_ui (e.g. black filled square, black filled circle), but at last I still choose this because it doesn't require any other fatty 3rd-party icon font (e.g. Material Design Icons), clear enough to emphasize titles, and portable enough across different OS. And at least, somewhat fit my personal aesthetic taste. So lazy as me I use all such UI pattern across all my WebExtensions
