### ISSUE TITLE
Pulldown menu

### ISSUE THREAD

**Issue by woutervanwijk** [kuanyui/EngineSwitcher#2]
Hi! Nice extension. One suggestion: when you click the icon that appears in the address bar, it cycles to the next engine. A pulldown menu where you can select the engine you want would be better from a usability point of view, imho

**Comment by kuanyui** [comment]
Have you tried to enable floating buttons? I feel this is already pretty usable.

**Comment by woutervanwijk** [comment]
It is pretty usable! I like it better than the icon :) But in UX terms, a floating button like this encapsulated in a webpage is not the most intuitive thing. 

Btw: if I switch to Brave, the bar disappears.

**Comment by kuanyui** [comment]
1. Because this WebExtension is mainly designed for mobile at first to avoiding typing `!g` on mobile when DuckDuckGo. Floating buttons at bottom are very convenient and intuitive on mobile, and I feel that's also good on desktop.
2. Actually the icon in the address bar (`browser.pageAction`) is just a legacy which I had been considering several times to remove it from this WebExtension . The reason is that WebExtension APIs for mobile is limited. Several years ago at the time I began to write this project, the `browser.pageAction` and the popup of it (`browser.pageAction.setPopup()`) is very inconvenient to use on mobile, so I don't implement it specially for desktop. So I decide to use a floating buttons bar because it can work both on mobile and desktop and provide same UI&UX. 
And nowadays the `browser.pageAction` seems totally removed from Fenix (Kotlin-rewritten Firefox for Android, since about 2020, had totally replaced the old version Firefox for Android, that is to say, currently only desktop Firefox supports `browser.pageAction`. NEVERTHELESS I still have no interest to implement this because the current floating buttons bar is handy enough both on desktop and mobile, at least for me.
3. I won't implement pulldown menu for `browser.pageAction` because I think it's unnecessary, and I have no free time to implement what I doesn't need **for free** and may still be rated *"not good enough"*, or complain *"why don't you implement the feature I want!"* (For free? Am I your employee? And I don't know why "working in free time" is so cheap in the eyes of the others.), or even merely revilement, I've enough of this sick FLOSS environment -- If you do something good, no reward, no applause; if you cannot satisfy some users, forced to receive lots of bad emotions which makes me feel down. I've been tired. Yeah I know I'm also complaining, but I just want to let you understand the reason of this decision. If you really need this feature, please consider to send a PR. I'm going to close this issue.

---

Last but not the least, thanks for the issue report of Brave,  It seems because that they modified the behavior of DOM, now fixed. Please wait for the next release from Mozilla Addons.

**Comment by woutervanwijk** [comment]
I didn't mean to offense you of course :) I maintained a popular FOSS product and it sometimes was tiring indeed

Perfectly fine if you don't implement it. It was only a suggestion. Good luck!
